### ISSUE TITLE
"make" encounter error

### ISSUE THREAD

**Issue by luckypoem** [fantuz/DNSProxy#7]
HI.

yudeMacBook-Air:DNSProxy-by-fantuz brite$ make
gcc -w -c dnsp.c
gcc dnsp.o -O2 -Wall -W -pedantic -g -rdynamic -DTLS -L/usr/local/lib -lcurl -lpthread -lrt -w -o dnsp
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [dnsp] Error 1
yudeMacBook-Air:DNSProxy-by-fantuz brite$

how to fix it? tks

**Comment by fantuz** [comment]
hello @luckypoem did you try pulling again the repo ?
I had commit wrong code-base, excuse me !

Let me know if I can help,
Best regards,
Max

**Comment by luckypoem** [comment]
hi,

yudeMacBook-Air:DNSProxy-by-fantuz brite$ make
gcc -w -c dnsp.c
gcc dnsp.o -O2 -Wall -W -pedantic -g -rdynamic -DTLS -lcurl -lrt -lnghttp2 -lssl -lbrotlidec -lz -lcrypto -lpthread -w -o dnsp
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [dnsp] Error 1
yudeMacBook-Air:DNSProxy-by-fantuz brite$

i recloned the repo,but
still the same error,
how to fix it?
tks

**Comment by fantuz** [comment]
Hello @luckypoem try removing the RT flag
You can edit makefile and suppress "-lrt"

do not have a MACOS in hands to test ...

**Comment by fantuz** [comment]
hello @luckypoem please try again and follow updated README instructions !

best regards
Max

**Comment by fantuz** [comment]
## Build and Install

Build is easy on Linux, Mac, UNIX and probably even Windows; DNSProxy is based
on CURL C library, pthread, SSL/TLS and various other strong standards.
A recent version of CURL is needed to leverage HTTP/2 capabilities (aka nghttp2).

```bash
sudo apt-get install libcurl4-openssl-dev curl libsslcommon2-dev \
libssl-dev ca-certs brotli gnutls-bin openssl libtlsh-dev
```
```bash
git clone https://github.com/clibs/clib.git /tmp/clib
cd /tmp/clib
sudo make install
```
```bash
sudo clib install littlstar/b64.c
```

```bash
sudo clib install jwerle/libok
```
Once done with pre-requisites, you will be able to *compile* by running:
```bash
make
```
